=== Sunnyvess/nmbp-turisticki/turistickiXML/turistickiXML/XML/schema.xsd
<?xml version="1.0"?>

<xs:schema id="Turisticki" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="turistickiVodic">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gradovi" maxOccurs="unbounded"/>
				<xs:element ref="tipoviMuzeja" maxOccurs="unbounded"/>
				<xs:element ref="tipoviZnamenitosti" maxOccurs="unbounded"/>
				<xs:element ref="bolnice" maxOccurs="unbounded"/>
				<xs:element ref="muzeji" maxOccurs="unbounded"/>
				<xs:element ref="znamenitosti" maxOccurs="unbounded"/>
				<xs:element ref="parkovi" maxOccurs="unbounded"/>
			</xs:sequence>            
        </xs:complexType>
		<xs:key name="gradKeyConstraint">
			<xs:selector xpath="./gradovi/grad"/>
			<xs:field xpath="@pbr"/>
		</xs:key>
		<xs:keyref name="bolnicaGradConstraint" refer="gradKeyConstraint">
			<xs:selector xpath="./bolnice/bolnica"/>
			<xs:field xpath="@pbr"/>
		</xs:keyref>
		<xs:keyref name="muzejGradConstraint" refer="gradKeyConstraint">
			<xs:selector xpath="./muzeji/muzej"/>
			<xs:field xpath="@pbr"/>
		</xs:keyref>
		<xs:keyref name="znamenitostGradConstraint" refer="gradKeyConstraint">
			<xs:selector xpath="./znamenitosti/znamenitost"/>
			<xs:field xpath="@pbr"/>
		</xs:keyref>
		<xs:keyref name="parkGradConstraint" refer="gradKeyConstraint">
			<xs:selector xpath="./parkovi/park"/>
			<xs:field xpath="@pbr"/>
		</xs:keyref>
		<xs:key name="tipMuzejKeyConstraint">
			<xs:selector xpath="./tipoviMuzeja/tipMuzej"/>
			<xs:field xpath="@idTipMuzej"/>
		</xs:key>
		<xs:key name="tipZnamenitostKeyConstraint">
			<xs:selector xpath="./tipoviZnamenitosti/tipZnamenitost"/>
			<xs:field xpath="@idTipZnamenitost"/>
		</xs:key>
		<xs:keyref name="tipMuzejConstraint" refer="tipMuzejKeyConstraint">
			<xs:selector xpath="./muzeji/muzej"/>
			<xs:field xpath="@idTipMuzej"/>
		</xs:keyref>
		<xs:keyref name="tipZnamenitostConstraint" refer="tipZnamenitostKeyConstraint">
			<xs:selector xpath="./znamenitosti/znamenitost"/>
			<xs:field xpath="@idTipZnamenitost"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="gradovi">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="grad" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="grad">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nazivGrad" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="pbr" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="lokacijaT">
		<xs:sequence>
			<xs:element name="naziv" type="xs:string"/>
			<xs:element name="ulica" type="xs:string"/>
			<xs:element name="opis" type="xs:string"/>
			<xs:element name="radnoVrijeme" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="pbr" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="bolnicaT">
		<xs:complexContent>
			<xs:extension base="lokacijaT">
				<xs:attribute name="idBolnica" type="xs:integer" use="required"/>
				<xs:attribute name="dezurstvo" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="muzejT">
		<xs:complexContent>
			<xs:extension base="lokacijaT">
				<xs:attribute name="idMuzej" type="xs:integer" use="required"/>
				<xs:attribute name="tipMuzeja" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="znamenitostT">
		<xs:complexContent>
			<xs:extension base="lokacijaT">
				<xs:sequence>
					<xs:element name="datumIzgradnje" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="idZnamenitost" type="xs:integer" use="required"/>
				<xs:attribute name="tipZnamenitost" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="parkT">
		<xs:complexContent>
			<xs:extension base="lokacijaT">
				<xs:attribute name="idPark" type="xs:integer" use="required"/>
				<xs:attribute name="otvoren" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:element name="tipoviMuzeja">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipMuzej" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tipMuzej">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nazivTipMuzej"/>
			</xs:sequence>
			<xs:attribute name="idTipMuzej" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tipoviZnamenitosti">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipZnamenitost" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tipZnamenitost">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nazivTipZnamenitost"/>
			</xs:sequence>
			<xs:attribute name="idTipZnamenitost" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bolnice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bolnica" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bolnica" type="bolnicaT">
		<xs:key name="bolnicaKeyConstraint">
			<xs:selector xpath="./bolnice/bolnica"/>
			<xs:field xpath="@idBolnica"/>
		</xs:key>
	</xs:element>
	
	<xs:element name="muzeji">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="muzej" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="muzej" type="muzejT">
		<xs:key name="muzejKeyConstraint">
			<xs:selector xpath="./muzeji/muzej"/>
			<xs:field xpath="@idMuzej"/>
		</xs:key>
	</xs:element>
	
	<xs:element name="znamenitosti">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="znamenitost" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="znamenitost" type="znamenitostT">
		<xs:key name="znamenitostKeyConstraint">
			<xs:selector xpath="./znamenitosti/znamenitost"/>
			<xs:field xpath="@idZnamenitost"/>
		</xs:key>
	</xs:element>
	
	<xs:element name="parkovi">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="park" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="park" type="parkT">
		<xs:key name="parkKeyConstraint">
			<xs:selector xpath="./parkovi/park"/>
			<xs:field xpath="@idPark"/>
		</xs:key>
	</xs:element>
	
</xs:schema>

=== Sunnyvess/nmbp-turisticki/turistickiXML/turistickiXML/XML/turistickiVodic.xml
<?xml version="1.0"?>

<turistickiVodic
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">
	<gradovi>
		<grad pbr="10000">
			<nazivGrad>Zagreb</nazivGrad>
		</grad>
		<grad pbr="21000">
			<nazivGrad>Split</nazivGrad>
		</grad>
    <grad pbr="22000">
      <nazivGrad>Osijek</nazivGrad>
    </grad>
	</gradovi>
	<bolnice>
		<bolnica id="1" pbr="10000" dezurstvo="DA">
			<naziv>Rebro</naziv>
			<ulica>Jukićeva 33</ulica>
			<opis>Ovo je opis bolnice Rebro.</opis>
			<radnoVrijeme>0-24</radnoVrijeme>
		</bolnica>
    <bolnica id="2" pbr="21000" dezurstvo="DA">
      <naziv>Javna Bolnica</naziv>
      <ulica>Kerumova ulica 33</ulica>
      <opis>Ovo je opis bolnice ove.</opis>
      <radnoVrijeme>0-24</radnoVrijeme>
    </bolnica>
	</bolnice>
	<muzeji>
		<muzej id="1" pbr="10000" tipMuzeja="Umjetnički">
			<naziv>Muzej suvremene umjetnosti</naziv>
			<ulica>Trg hrvatskih velikana 7</ulica>
			<opis>Ovo je opis Muzeja suvremene umjetnosti.</opis>
			<radnoVrijeme>8-20</radnoVrijeme>
		</muzej>
	</muzeji>
	<znamenitosti>
		<znamenitost id="1" pbr="21000" tipZnamenitost="Tvrđava">
			<naziv>Dioklecijanova palača</naziv>
			<ulica>Ante Starčevića 68</ulica>
			<opis>Ovo je opis Dioklecijanove palače.</opis>
			<radnoVrijeme>0-24</radnoVrijeme>
			<datumIzgradnje>295.g.</datumIzgradnje>
		</znamenitost>
	</znamenitosti>
	<parkovi>
		<park id="1" pbr="10000" otvoren="DA">
			<naziv>Zrinjevac</naziv>
			<ulica>Zrinjevac 8</ulica>
			<opis>Ovo je opis Zrinjevca.</opis>
			<radnoVrijeme>0-24</radnoVrijeme>
		</park>
	</parkovi>
</turistickiVodic>
