=== Sunnyvess/nmbp-turisticki/trunk/turistickiXML/turistickiXML/XML/schema.xsd
<?xml version="1.0"?>

<xs:schema id="Turisticki" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="naziv" type="xs:string"/>
  <xs:element name="ulica" type="xs:string"/>
  <xs:element name="opis" type="xs:string"/>
  <xs:element name="radnoVrijeme" type="xs:string"/>
  <xs:element name="datumIzgradnje" type="xs:date"/>

  <xs:attribute name="id" type="xs:integer"/>
  <xs:attribute name="pbr" type="xs:integer"/>

  <xs:attribute name="dezurstvo" type="myboolean"/>
  <xs:attribute name="otvoren" type="myboolean"/>
  <xs:attribute name="tipMuzeja" type="tipMuzejaT"/>
  <xs:attribute name="tipZnamenitost" type="tipZnamenitostiT"/>

  <xs:simpleType name="myboolean">
    <xs:restriction base="xs:string">
      <xs:enumeration value="True"/>
      <xs:enumeration value="False"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipMuzejaT">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Prirodoslovni"/>
      <xs:enumeration value="Arheološki" />
      <xs:enumeration value="Tehnički" />
      <xs:enumeration value="Povijesni" />
      <xs:enumeration value="Umjetnički" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipZnamenitostiT">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Tvrđava"/>
      <xs:enumeration value="Spomenik" />
      <xs:enumeration value="Crkva" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="grad">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naziv" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="pbr" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="gradovi">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="grad" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="lokacijaT">
    <xs:sequence>
      <xs:element ref="naziv"/>
      <xs:element ref="ulica"/>
      <xs:element ref="opis"/>
      <xs:element ref="radnoVrijeme"/>
    </xs:sequence>
    <xs:attribute ref="id" use="required"/>
    <xs:attribute ref="pbr" use="required"/>
  </xs:complexType>

  <xs:complexType name="bolnicaT">
    <xs:complexContent>
      <xs:extension base="lokacijaT">
        <xs:attribute ref="dezurstvo" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="muzejT">
    <xs:complexContent>
      <xs:extension base="lokacijaT">
        <xs:attribute ref="tipMuzeja" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="znamenitostT">
    <xs:complexContent>
      <xs:extension base="lokacijaT">
        <xs:sequence>
          <xs:element ref="datumIzgradnje"/>
        </xs:sequence>
        <xs:attribute ref="tipZnamenitost" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="parkT">
    <xs:complexContent>
      <xs:extension base="lokacijaT">
        <xs:attribute ref="otvoren" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="bolnica" type="bolnicaT"/>
  <xs:element name="muzej" type="muzejT"/>
  <xs:element name="znamenitost" type="znamenitostT"/>
  <xs:element name="park" type="parkT"/>

  <xs:element name="bolnice">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bolnica" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="muzeji">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="muzej" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="znamenitosti">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="znamenitost" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="parkovi">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="park" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
	<xs:element name="turistickiVodic">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gradovi" maxOccurs="unbounded"/>
				<xs:element ref="bolnice" maxOccurs="unbounded"/>
				<xs:element ref="muzeji" maxOccurs="unbounded"/>
				<xs:element ref="znamenitosti" maxOccurs="unbounded"/>
				<xs:element ref="parkovi" maxOccurs="unbounded"/>
			</xs:sequence>            
     </xs:complexType>
    
		<xs:key name="gradKeyConstraint">
			<xs:selector xpath="./gradovi/grad"/>
			<xs:field xpath="@pbr"/>
		</xs:key>
    <xs:keyref name="lokacijaGradConstraint" refer="gradKeyConstraint">
      <xs:selector xpath="./bolnice/bolnica | ./muzeji/muzej | ./parkovi/park | ./znamenitosti/znamenitost"/>
      <xs:field xpath="@pbr"/>
    </xs:keyref>
    <xs:key name="bolnicaKeyConstraint">
      <xs:selector xpath="./bolnice/bolnica"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="muzejKeyConstraint">
      <xs:selector xpath="./muzeji/muzej"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="znamenitostKeyConstraint">
      <xs:selector xpath="./znamenitosti/znamenitost"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="parkKeyConstraint">
      <xs:selector xpath="./parkovi/park"/>
      <xs:field xpath="@id"/>
    </xs:key>
	</xs:element>
	
</xs:schema>

=== Sunnyvess/nmbp-turisticki/trunk/turistickiXML/turistickiXML/XML/turistickiVodic.xml
<?xml version="1.0"?>
<turistickiVodic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
  <gradovi>
    <grad pbr="10000">
      <naziv>Zagreb</naziv>
    </grad>
    <grad pbr="21000">
      <naziv>Split</naziv>
    </grad>
    <grad pbr="22000">
      <naziv>Osijek</naziv>
    </grad>
  </gradovi>
  <bolnice>
    <bolnica id="1" pbr="10000" dezurstvo="False">
      <naziv>Rebro</naziv>
      <ulica>Jukićeva 33</ulica>
      <opis>Ovo je opis bolnice Rebro.</opis>
      <radnoVrijeme>0-24</radnoVrijeme>
    </bolnica>
    <bolnica id="2" pbr="21000" dezurstvo="True">
      <naziv>Klinički bolnički centar Split</naziv>
      <ulica>Spinčićeva 1</ulica>
      <opis>
      </opis>
      <radnoVrijeme>
      </radnoVrijeme>
    </bolnica>
    <bolnica id="3" pbr="10000" dezurstvo="True">
      <naziv>KBC Zagreb</naziv>
      <ulica>Šalata 6</ulica>
      <opis>
      </opis>
      <radnoVrijeme>0-24</radnoVrijeme>
    </bolnica>
  </bolnice>
  <muzeji>
    <muzej id="1" pbr="10000" tipMuzeja="Arheološki">
      <naziv>Muzej suvremene umjetnosti</naziv>
      <ulica>Trg hrvatskih velikana 6</ulica>
      <opis>Ovo je opis Muzeja suvremene umjetnosti.</opis>
      <radnoVrijeme>8-20</radnoVrijeme>
    </muzej>
  </muzeji>
  <znamenitosti>
    <znamenitost id="1" pbr="21000" tipZnamenitost="Tvrđava">
      <naziv>Dioklecijanova palača</naziv>
      <ulica>Ante Starčevića 68</ulica>
      <opis>Ovo je opis Dioklecijanove palače.</opis>
      <radnoVrijeme>0-24</radnoVrijeme>
      <datumIzgradnje>2011-12-08</datumIzgradnje>
    </znamenitost>
  </znamenitosti>
  <parkovi>
    <park id="1" pbr="10000" otvoren="False">
      <naziv>Zrinjevac</naziv>
      <ulica>Zrinjevac 8</ulica>
      <opis>Ovo je opis Zrinjevca.</opis>
      <radnoVrijeme>0-24</radnoVrijeme>
    </park>
  </parkovi>
</turistickiVodic>
